---
- name: Include ppc tasks
  include_tasks: setup-ppc.yml
  when: ansible_architecture == "ppc64le"

- name: Include z series tasks
  include_tasks: setup-z.yml
  when: ansible_architecture == "s390x"

- name: Include other architecture tasks
  include_tasks: setup-other.yml
  when:
    - ansible_architecture != "ppc64le"
    - ansible_architecture != "s390x"

- name: Create version file
  become: true
  copy:
    content: "{{ java_toolchain_sha }}"
    dest: "{{ java_toolchain_final_dest }}/toolchain_version"
