---
- name: Remove old toolchain
  become: true
  file:
    path: "{{ java_toolchain_final_dest }}"
    state: absent
  when:
    - toolchain_archive_contents.changed

- name: Move java directory from tmp to opt
  become: true
  command: mv /tmp/java {{ java_toolchain_final_dest }}
  when:
    - toolchain_archive_contents.changed
