---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: archlinux
    image: archlinux:latest
  - name: debian9
    image: debian:9
  - name: debian10
    image: debian:10
  - name: rhel8
    image: registry.redhat.io/ubi8
  - name: rhel7
    image: registry.redhat.io/ubi7
  - name: rhel6
    image: registry.redhat.io/rhel6
provisioner:
  name: ansible
verifier:
  name: testinfra
