---
- become: true
  name: Converge
  hosts: all
  roles:
    - role: ansible-role-java-toolchain
      vars:
        java_toolchain_sha: testing_java_sha
        java_toolchain_url: https://ansible-molecule-test.s3.amazonaws.com/test_javatoolchain.tar.gz
