---
jobs:
  test:
    name: molecule test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install required dependencies
        run: pip install -r requirements.txt
      - run: molecule test --all
        env:
          ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD}}
name: Molecule Test
'on':
  - push
